# web server
nginx:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    restart: always
    volumes:
        # app
        - ./app:/usr/share/nginx/html
        # nginx configs
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        - ./logs/nginx:/var/log/nginx
    links:
        - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
    build: ./php-fpm
    ports:
        - "9000"
    volumes:
        - ./app:/usr/share/nginx/html
        # Your php.ini
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
        ### php log file
        - ./logs/php:/var/log/fpm
        # environment:
        # Set your APP env variables here:
        # - APP_KEY=
        # - DB_HOST=
        # - DB_DATABASE=
        # - DB_USERNAME=
        # - DB_PASSWORD=
    links:
        - mysql:database_local

# database
mysql:
    image: mysql:latest
    ports:
        # Allow client to access 3306
        - "3306:3306"
    volumes:
        # NOTE: your data will be stored in ./mysql
        - ./mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root123
